<?php

namespace mohamed\MyAppBundle\Entity;

use Acme\BlogBundle\Entity\Stage;
use Doctrine\Common\Persistence\ObjectManager;
/**
 * studentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class studentRepository extends \Doctrine\ORM\EntityRepository
{

	

}
