<?php

namespace etu\doctrineBundle\Entity;

/**
 * departementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class departementRepository extends \Doctrine\ORM\EntityRepository
{
}
