<?php

namespace etu\doctrineBundle\Entity;

/**
 * regionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regionRepository extends \Doctrine\ORM\EntityRepository
{
}
