<?php

namespace dciss\MyApp\BlogBundle\Entity;

use Doctrine\Common\Persistence\ObjectManager;
/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

}
